name: cooper_tec
description: Flutter case study built for CooperTec's technical interview.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  flutter_lints: ^4.0.0
  mocktail: ^1.0.3
flutter:
  assets:
    - assets/
  uses-material-design: true
