name: cooper_tec
description: Projeto para a CooperTec.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  crypto:
  cupertino_icons: ^1.0.2
  get_it:
  dartz:
  equatable:
  flutter_bloc:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/
  uses-material-design: true
